pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'github_username_password', 
                url: 'https://github.com/testdev89/Docker-Zero-to-Hero.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    dockerImage = docker.build("mukesh123/python-webapp:${IMAGE_TAG}", "./examples/python-web-app/")
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
                      dockerImage.push()
                    }
                }
            }
        }
        
    }
}
